### ISSUE TITLE
Non-conda folder exists at prefix

### ISSUE THREAD

**Issue by dzhu8** [EngreitzLab/scE2G#39]
Hi, when trying to run snakemake, I get this error: 

![image](https://github.com/user-attachments/assets/e84cdf6c-ad94-42e3-af72-4407fcb4c525)

The only major difference on the scE2G directory side is the config file, which I have attached in the form of a text file in case this may be leading to issues: 
[config.txt](https://github.com/user-attachments/files/17987336/config.txt)

Let me know if anything else would be helpful to diagnose this!

**Comment by 613weilin** [comment]
Hi @dzhu8, thank you for reporting this issue.

The error could be related to the version of mamba. Could you try specifying the mamba version when creating the environment? Use the following command:
`conda create -n mamba -c conda-forge mamba=1.5.11 "python<=3.11"`

**Comment by 613weilin** [comment]
Update the README
