### ISSUE TITLE
Could not create conda environment from sc_e2g.yml

### ISSUE THREAD

**Issue by Yanbo-Xu** [EngreitzLab/scE2G#45]
HI!
I saw the previously resolved issue and specified the version of mamba and python to create the environment. But unfortunately, I'm still experiencing a similar error. How can we resolve?🥲
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/4bac00bb-494c-449a-9c63-bb666dbc7699" />

**Comment by Yanbo-Xu** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/d26b1504-7a47-45e5-8398-cdae9fa005eb" />

**Comment by 613weilin** [comment]
Hi @Yanbo-Xu, could you check your mamba version using the command `conda list`?

**Comment by Yanbo-Xu** [comment]
of course 
<img width="714" alt="image" src="https://github.com/user-attachments/assets/d4cdbaf8-2ba1-4d38-bee8-adf7f8cb37ce" />

**Comment by 613weilin** [comment]
Thanks! Could you try running `mamba env create --quiet --file "/home/xuyanbo/software/scE2G/.snakemake/conda/89af5479044d93a6218c0bf65811b986_.yaml" --prefix "/home/xuyanbo/software/scE2G/.snakemake/conda/89af5479044d93a6218c0bf65811b986_"` manually?

**Comment by Yanbo-Xu** [comment]
In fact I tried it earlier and the task gets killed when setting up the environment. is it because of lack of memory?
<img width="691" alt="image" src="https://github.com/user-attachments/assets/6ef9de60-e37b-49ef-b116-57a8eebb99b1" />

**Comment by 613weilin** [comment]
I am unsure if it is a memory issue. Perhaps you can add `--verbose` during the mamba env create command (e.g., `mamba env create --quiet --file "/home/xuyanbo/software/scE2G/.snakemake/conda/89af5479044d93a6218c0bf65811b986_.yaml" --prefix "/home/xuyanbo/software/scE2G/.snakemake/conda/89af5479044d93a6218c0bf65811b986_" --verbose`) to get more information. Also, monitor the memory using `top` or `htop` commands during the installation process.

**Comment by Yanbo-Xu** [comment]
OK! I am increasing the memory request to retry the task and also using `htop` to check the memory usage. I'll update if there is any progress!🤗

**Comment by Yanbo-Xu** [comment]
Hi Weilin, I increased memory and the previous problem did not occur. But there are very many dependency conflicts, is this due to my conda configuration?
(The image captures only a portion of the error message)
<img width="872" alt="image" src="https://github.com/user-attachments/assets/b705c2f5-262d-47d5-aff5-cf68af711eb6" />

**Comment by Yanbo-Xu** [comment]
Hi! I just ran it successfully and got the output file `encode_e2g_predictions.tsv` as shown in the screenshot below, is this running correctly?
I used 10 cores and 40 gigs of ram and it took about 3 hours, is this normal?
<img width="937" alt="image" src="https://github.com/user-attachments/assets/2ab00f0c-116e-4a4d-a260-245daf6e056b" />

**Comment by Yanbo-Xu** [comment]
Thanks for your help!!🥰
