### ISSUE TITLE
Problems with atac_powerlaw path not existing

### ISSUE THREAD

**Issue by Yanbo-Xu** [EngreitzLab/scE2G#47]
Hi, I just tried to run the multiome_powerlaw_v2 model, but got an error showing that the path doesn't exist, an error that didn't appear in my previous run. Does this path need to be changed to `models/multiome_powerlaw_v2`?

```
/home/xuyanbo/software/scE2G/ENCODE_rE2G/ABC/workflow/rules/utils.smk:86: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  _configure_tss_and_gene_files(biosamples_config)
Exception in file /home/xuyanbo/software/scE2G/ENCODE_rE2G/workflow/rules/utils.smk, line 159:
/home/xuyanbo/software/scE2G/models/atac_powerlaw not found. Model with input params not supported
  File "/home/xuyanbo/software/scE2G/workflow/Snakefile", line 55, in <module>
  File "/home/xuyanbo/software/scE2G/ENCODE_rE2G/workflow/Snakefile", line 57, in <module>
  File "/home/xuyanbo/software/scE2G/ENCODE_rE2G/workflow/rules/utils.smk", line 85, in expand_biosample_df
  File "/home/xuyanbo/software/scE2G/ENCODE_rE2G/workflow/rules/utils.smk", line 159, in _get_biosample_model_dir_from_row
```

**Comment by 613weilin** [comment]
The possible reason for this issue is that the `model_dir` column in `scE2G/config/config_cell_clusters.tsv` is set to `models/atac_powerlaw`. 
If you want to run the `multiome_powerlaw_v2` model, you should set it to `models/multiome_powerlaw_v2`. Alternatively, if you want to run the `scATAC_powerlaw_v2` model, it should be set to `models/scATAC_powerlaw_v2`.

**Comment by Yanbo-Xu** [comment]
I checked `scE2G/config/config_cell_clusters.tsv` before and the mods setting was not set to atac_powerlaw. i solved the problem by reinstalling the whole repository, it could be some bias
